### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by eljeffeg** [fukayatsu/heroku-dyno-restarter#4]
I'd like to install this, but I don't understand the instructions for getting it running.  I have Heroku, I have the PaperTrail addon and I see webhooks (requires URL), I have a Redis addon.  What do I need to do?

**Comment by fukayatsu** [comment]
@jeffg2k 

Sorry for the late reply.
You may want to try https://github.com/fukayatsu/heroku-dyno-restarter#configuration (Introduced by #8 ).
